### ISSUE TITLE
An error occurred while running the command `yarn run deploy`

### ISSUE THREAD

**Issue by jjz** [matter-labs/zksync-hardhat-template#3]
```
HardhatError: HH700: Artifact for contract "Greeter" not found.
    at Artifacts._handleWrongArtifactForContractName (/root/zksync-hardhat-template/node_modules/hardhat/src/internal/artifacts.ts:702:11)
    at Artifacts._getArtifactPathFromFiles (/root/zksync-hardhat-template/node_modules/hardhat/src/internal/artifacts.ts:827:19)
    at Artifacts._getArtifactPath (/root/zksync-hardhat-template/node_modules/hardhat/src/internal/artifacts.ts:507:21)
    at async Artifacts.readArtifact (/root/zksync-hardhat-template/node_modules/hardhat/src/internal/artifacts.ts:71:26)
    at async Deployer.loadArtifact (/root/zksync-hardhat-template/node_modules/@matterlabs/hardhat-zksync-deploy/src/deployer.ts:116:26)
    at async default_1 (/root/zksync-hardhat-template/deploy/deploy-greeter.ts:25:20)
    at async runScript (/root/zksync-hardhat-template/node_modules/@matterlabs/hardhat-zksync-deploy/src/plugin.ts:73:5)
    at async callDeployScripts (/root/zksync-hardhat-template/node_modules/@matterlabs/hardhat-zksync-deploy/src/plugin.ts:50:17)
    at async SimpleTaskDefinition.zkSyncDeploy [as action] (/root/zksync-hardhat-template/node_modules/@matterlabs/hardhat-zksync-deploy/src/task-actions.ts:5:5)
    at async Environment._runTaskDefinition (/root/zksync-hardhat-template/node_modules/hardhat/src/internal/core/runtime-environment.ts:311:14)
```
When running the command `yarn hardhat compile`, only the following message appears without compiling the contracts.
```
/root/zksync-hardhat-template/node_modules/.bin/hardhat compile
Downloading solc 0.8.17
Done in 0.92s.
```

**Comment by uF4No** [comment]
have you installed the dependencies running `yarn`? 
Have you modified the `hardhat.config.ts`? Please share it because it looks like it's compiling the contracts with solc and not with zksolc.

**Comment by jjz** [comment]
> have you installed the dependencies running `yarn`? Have you modified the `hardhat.config.ts`? Please share it because it looks like it's compiling the contracts with solc and not with zksolc.

Yes, I have installed Yarn and I am using the config as it is in the code without any modifications.
```
import { HardhatUserConfig } from "hardhat/config";

import "@matterlabs/hardhat-zksync-deploy";
import "@matterlabs/hardhat-zksync-solc";

// dynamically changes endpoints for local tests
const zkSyncTestnet =
  process.env.NODE_ENV == "test"
    ? {
        url: "http://localhost:3050",
        ethNetwork: "http://localhost:8545",
        zksync: true,
      }
    : {
        url: "https://zksync2-testnet.zksync.dev",
        ethNetwork: "goerli",
        zksync: true,
      };

const config: HardhatUserConfig = {
  zksolc: {
    version: "1.3.8",
    compilerSource: "binary",
    settings: {},
  },
  defaultNetwork: "zkSyncTestnet",
  networks: {
    hardhat: {
      zksync: false,
    },
    zkSyncTestnet,
  },
  solidity: {
    version: "0.8.17",
  },
};

export default config;

```

**Comment by dutterbutter** [comment]
Hey @jjz are you still facing issues here?

**Comment by JackHamer09** [comment]
Closing this issue because of inactivity.
